{% set name = "language-tool-python" %}
{% set name2 = "language_tool_python" %}
{% set version = "2.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name2 }}/{{ name2 }}-{{ version }}.tar.gz"
  sha256: d6888189b784f91fc885ba6ac0c3e0f397e9f5ac0afe1daece72aca7afdeb696

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - requests
    - tqdm
    - python

test:
  imports:
    - language_tool_python

about:
  home: https://github.com/jxmorris12/language_tool_python
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: a grammar checker for Python
  doc_url: https://pypi.org/project/language-tool-python/
  dev_url: https://github.com/jxmorris12/language_tool_python

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
