{% set name = "pydp" %}
{% set version = "0.1.1dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
  sha256: 2580e986cfff2edb7667d68835cc22115aa7e7e595535a647ec4e34d5755a703

build:
  number: 0
  # script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [osx]

requirements:
  build:
    - bazel
    - pipenv
  host:
    - python
    - pipenv
    - pip
    - pytest
  run:
    - python
    - pytest

test:
  source_files:
    - pydp
  imports:
    - pydp

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - oblute
    - rluria14
