
{% set name = "pydp" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
  sha256: 89311de8acd83d9b1cd672804683cf7d1632e9d2ec2fd5f9c71aec640163ed57

build:
  number: 0
  script: 
   - git submodule update --init --recursive
   - ls 
   - ls third_party
   - ls third_party/differential-privacy
   - ls third_party/differential-privacy/cc
   - ./prereqs_mac.sh  # [osx]
   - ./prereqs_linux.sh  # [linux]
   - ./build_PyDP.sh
   - {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bazel
  host:
    - python
    - pip
    - pytest
    - poetry
  run:
    - python
    - poetry
    - pytest

test:
  imports:
    - pydp

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar