
{% set name = "pydp" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
  sha256: 89311de8acd83d9b1cd672804683cf7d1632e9d2ec2fd5f9c71aec640163ed57

build:
  number: 0
  script: 
    # - git submodule update --init --recursive
    # - cd ../../
    # - echo "ls"
    # - ls 
    # - echo "tp"
    # - ls third_party
    # - echo "tp/dp"
    # - ls third_party/differential-privacy
    # - echo "tp/dp/cc"
    # - ls third_party/differential-privacy/cc
    # - echo "RUN PREREQS"
    # - ./prereqs_mac.sh  # [osx]
    # - ./prereqs_linux.sh  # [linux]
    # - echo "RUN BUILD PYDP"
    # - ./build_PyDP.sh
    # - echo "BOULD PYDP"
    - echo "THIRD PARTY"
    - mkdir -p third_party && cd third_party && git clone https://github.com/google/differential-privacy.git && cd differential-privacy
    - cd ../../
    - echo "PWD"
    - pwd
    - echo "BAZEL CMD"
    # - bazel coverage src/python:bindings_test --config linux --verbose_failures --action_env=PYTHON_BIN_PATH=$PYTHON --action_env=PYTHON_LIB_PATH=$PYTHON  # [linux]
    # - bazel coverage src/python:bindings_test --config macos --verbose_failures --action_env=PYTHON_BIN_PATH=$PYTHON --action_env=PYTHON_LIB_PATH=$PYTHON  # [osx]
    - PYTHONPATH=$($PYTHON -c 'import sys; print([x for x in sys.path if "site-packages" in x][0]);')
    - bazel coverage src/python:bindings_test --verbose_failures --action_env=PYTHON_BIN_PATH=$PYTHON --action_env=PYTHON_LIB_PATH=$PYTHONPATH  # [linux]
    - bazel coverage src/python:bindings_test --verbose_failures --action_env=PYTHON_BIN_PATH=$PYTHON --action_env=PYTHON_LIB_PATH=$PYTHONPATH  # [osx]
    - echo "PYTHON BUILD CMD"
    - {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bazel <4.0
    - grpc-cpp
    - googleapis-common-protos-grpc
    - clang
    - networkx >=2.5
  host:
    - googleapis-common-protos-grpc
    - clang
    - grpc-cpp
    - python
    - pip
    - pytest
    - poetry
    - networkx >=2.5
  run:
    - networkx >=2.5
    - googleapis-common-protos-grpc
    - clang
    - grpc-cpp
    - python
    - poetry
    - pytest

test:
  imports:
    - pydp

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar