
{% set name = "pydp" %}
{% set version = "0.1.4dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
  sha256: 9cc736b453fa65ed0a97a89b95a54349fae229bba98e0c761335c81fabadbabb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bazel
  host:
    - python
    - pip
    - pytest
  run:
    - python
    - pytest

test:
  imports:
    - pydp

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar