{% set name = "sentencepiece" %}
{% set version = "0.1.91" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: acbc7ea12713cd2a8d64892f8d2033c7fd2bb4faecab39452496120ace9a4b1b

build:
  number: 1
  skip: True  # [py<36 or osx]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - pkg-config
    - gperftools  # [not win]
    - pthreads-win32  # [win]
    - make
  host:
    - pip
    - python
    - pthreads-win32  # [win]
    - gperftools  # [not win]
  run:
    - python
    - gperftools  # [not win]

test:
  imports:
    - sentencepiece
  commands:
    - spm_export_vocab --help
    - spm_normalize --help

about:
  home: "https://github.com/google/sentencepiece/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training."

extra:
  recipe-maintainers:
    - setu4993
