{% set name = "textattack" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QData/{{ name|title }}/archive/{{ version }}.tar.gz
  sha256: db771ac4978c0e70f891c47770b8e2c0c1230ed7aecb47cec6979fd538f16bc6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bert_score # recipe auto
    - editdistance
    # - flair>=0.5.1 # try w/o
    - filelock
    - language_tool_python # recipe auto failed
    - lru-dict 
    - nltk
    - numpy
    - pandas>=1.0.1
    - scikit-learn
    - scipy==1.4.1
    - sentence-transformers
    - pytorch
    - transformers
    - tensorflow>=2
    - tensorflow_hub
    - tensorboardX
    - terminaltables
    - tokenizers
    - tqdm
    - visdom
    - wandb # recipe auto

test:
  commands:
    - textattack --help

about:
  home: https://github.com/QData/textattack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generating adversarial examples for NLP models
  doc_url: https://textattack.readthedocs.io/en/latest/
  dev_url: https://github.com/QData/textattack

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
  