{% set name = "deodr" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinResearch/DEODR/releases/download/v0.1.14/deodr-0.1.14.tar.gz
  sha256: d4c2a1997acf23835ca3003ea02bb63d3b294ad2908d9ce72cf78c6d0fcd42a4

build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  # noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  script: 
    - "{{ PYTHON }} setup.py build_ext --inplace"  # [win]
    - "{{ PYTHON }} setup.py build_ext"  # [not win]
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - numpy
    - scipy
    # - cython
    # - imageio
    # - trimesh
    # - opencv-python
    # - torch
    # - tensorflow
    # - moderngl
    # - pyrr
    # - pytest-xvfb

test:
  imports:
    - deodr

about:
  home: https://github.com/simplejson/simplejson
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: MIT
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: 
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

  # The remaining entries in this section are optional, but recommended.
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
